/**
 * AUTHORITATIVE CENTRAL SCHEMA — the single source of truth for what the
 * central PostgreSQL database must contain.
 *
 * This file is hand-maintained. It is intentionally NOT derived at runtime
 * from the local till schema: the till carries local-only bookkeeping
 * columns (is_synced, sync_status, last_error_at, …) and local-only tables
 * (sync_state, system_settings, transfers, shift_notifications) that must
 * never be demanded of the central database.
 *
 * Bump CENTRAL_SCHEMA_VERSION whenever this definition changes. It is
 * independent of the app version and the local database version.
 *
 * Column classification:
 *   required — the central database must have it; drift if absent.
 *   optional — used by some flows; reported but never blocks.
 *   legacy   — kept for historical data; never repaired, never dropped.
 */
export const CENTRAL_SCHEMA_VERSION = 1;

export type CentralColumnClass = "required" | "optional" | "legacy";

export type CentralColumnSpec = {
  name: string;
  /** PostgreSQL type, or a full additive fragment ("text not null default ''"). */
  pgType: string;
  classification?: CentralColumnClass;
};

export type CentralIndexSpec = {
  name: string;
  /** Full idempotent CREATE INDEX statement. */
  sql: string;
  /** Only emitted when one of these columns had to be repaired. */
  dependsOnColumns: string[];
};

export type CentralTableSchema = {
  table: string;
  label: string;
  primaryKey: string;
  columns: CentralColumnSpec[];
  indexes?: CentralIndexSpec[];
};

export const CENTRAL_SCHEMA: CentralTableSchema[] = [
  {
    table: "stores",
    label: "Branches",
    primaryKey: "id",
    columns: [
      { name: "id", pgType: "uuid" },
      { name: "code", pgType: "text" },
      { name: "name", pgType: "text" },
      { name: "address", pgType: "text" },
      { name: "phone", pgType: "text" },
      { name: "created_at", pgType: "timestamptz" },
      { name: "updated_at", pgType: "timestamptz" },
      { name: "group_id", pgType: "text" },
      { name: "row_version", pgType: "integer" },
      { name: "location_type", pgType: "text" },
      { name: "parent_id", pgType: "text" },
      { name: "is_central", pgType: "boolean" },
      { name: "building_name", pgType: "text" },
      { name: "floor_label", pgType: "text" },
      { name: "is_active", pgType: "boolean" },
      { name: "archived_at", pgType: "timestamptz" },
      { name: "is_primary_sub", pgType: "boolean" },
    ],
  },
  {
    table: "membership_tiers",
    label: "Membership tiers",
    primaryKey: "id",
    columns: [
      { name: "id", pgType: "uuid" },
      { name: "name", pgType: "text" },
      { name: "discount_percentage", pgType: "numeric(9,4)" },
      { name: "points_multiplier", pgType: "numeric(9,4)" },
      { name: "created_at", pgType: "timestamptz" },
      { name: "updated_at", pgType: "timestamptz" },
      { name: "row_version", pgType: "integer" },
    ],
  },
  {
    table: "products",
    label: "Products",
    primaryKey: "id",
    columns: [
      { name: "id", pgType: "uuid" },
      { name: "barcode", pgType: "text" },
      { name: "name", pgType: "text" },
      { name: "category", pgType: "text" },
      { name: "cost_price", pgType: "numeric(18,4)" },
      { name: "selling_price", pgType: "numeric(18,4)" },
      { name: "ecom_price", pgType: "numeric(18,4)" },
      { name: "stock_quantity", pgType: "integer" },
      { name: "custom_points", pgType: "numeric(18,4)" },
      { name: "point_multiplier", pgType: "numeric(9,4)" },
      { name: "created_at", pgType: "timestamptz" },
      { name: "sku", pgType: "text" },
      { name: "reorder_level", pgType: "integer" },
      { name: "tax_rate", pgType: "numeric(9,4)" },
      { name: "ecom_visible", pgType: "boolean" },
      { name: "stock_by_store", pgType: "jsonb" },
      { name: "updated_at", pgType: "timestamptz" },
      { name: "landing_pct", pgType: "numeric(18,4)" },
      { name: "sub_category", pgType: "text" },
      { name: "unit", pgType: "text" },
      { name: "packs", pgType: "jsonb" },
      { name: "barcode_aliases", pgType: "text[]" },
      { name: "is_archived", pgType: "boolean" },
      { name: "archived_at", pgType: "timestamptz" },
      { name: "brand", pgType: "text" },
      { name: "product_group", pgType: "text" },
      { name: "barcode_variants", pgType: "jsonb" },
      { name: "row_version", pgType: "integer" },
    ],
  },
  {
    table: "product_barcodes",
    label: "Barcodes",
    primaryKey: "id",
    columns: [
      { name: "id", pgType: "text" },
      { name: "product_id", pgType: "text" },
      { name: "barcode", pgType: "text" },
      { name: "label", pgType: "text" },
      { name: "pack_size", pgType: "numeric(18,4)" },
      { name: "is_primary", pgType: "boolean" },
      { name: "created_at", pgType: "timestamptz" },
      { name: "updated_at", pgType: "timestamptz" },
      { name: "row_version", pgType: "integer" },
    ],
  },
  {
    table: "product_categories",
    label: "Categories",
    primaryKey: "id",
    columns: [
      { name: "id", pgType: "text" },
      { name: "name", pgType: "text" },
      { name: "parent_id", pgType: "uuid" },
      { name: "sort", pgType: "integer" },
      { name: "created_at", pgType: "timestamptz" },
      { name: "updated_at", pgType: "timestamptz" },
      { name: "kind", pgType: "text" },
      { name: "row_version", pgType: "integer" },
    ],
  },
  {
    table: "uom_units",
    label: "Units of measure",
    primaryKey: "id",
    columns: [
      { name: "id", pgType: "text" },
      { name: "code", pgType: "text" },
      { name: "name", pgType: "text" },
      { name: "allow_decimal", pgType: "boolean" },
      { name: "sort", pgType: "integer" },
      { name: "created_at", pgType: "timestamptz" },
      { name: "updated_at", pgType: "timestamptz" },
      { name: "row_version", pgType: "integer" },
    ],
  },
  {
    table: "members",
    label: "Members",
    primaryKey: "id",
    columns: [
      { name: "id", pgType: "uuid" },
      { name: "member_code", pgType: "text" },
      { name: "full_name", pgType: "text" },
      { name: "phone", pgType: "text" },
      { name: "email", pgType: "text" },
      { name: "address", pgType: "text" },
      { name: "date_of_birth", pgType: "date" },
      { name: "tier_id", pgType: "uuid" },
      { name: "loyalty_points", pgType: "numeric(18,4)" },
      { name: "total_spent", pgType: "numeric(18,4)" },
      { name: "created_at", pgType: "timestamptz" },
      { name: "updated_at", pgType: "timestamptz" },
      { name: "row_version", pgType: "integer" },
      { name: "is_verified", pgType: "boolean" },
      { name: "verified_at", pgType: "timestamptz" },
      { name: "verified_channel", pgType: "text" },
    ],
  },
  {
    table: "promotions",
    label: "Promotions",
    primaryKey: "id",
    columns: [
      { name: "id", pgType: "uuid" },
      { name: "title", pgType: "text" },
      { name: "promo_type", pgType: "text" },
      { name: "min_spend", pgType: "numeric(18,4)" },
      { name: "discount_percent", pgType: "numeric(9,4)" },
      { name: "discount_amount", pgType: "numeric(18,4)" },
      { name: "foc_product_id", pgType: "uuid" },
      { name: "points_per_dollar", pgType: "numeric(9,4)" },
      { name: "tier_rates", pgType: "jsonb" },
      { name: "is_active", pgType: "boolean" },
      { name: "start_date", pgType: "date" },
      { name: "end_date", pgType: "date" },
      { name: "created_at", pgType: "timestamptz" },
      { name: "updated_at", pgType: "timestamptz" },
      { name: "row_version", pgType: "integer" },
    ],
  },
  {
    table: "suppliers",
    label: "Suppliers",
    primaryKey: "id",
    columns: [
      { name: "id", pgType: "uuid" },
      { name: "name", pgType: "text" },
      { name: "contact_name", pgType: "text" },
      { name: "phone", pgType: "text" },
      { name: "email", pgType: "text" },
      { name: "address", pgType: "text" },
      { name: "tax_number", pgType: "text" },
      { name: "notes", pgType: "text" },
      { name: "is_active", pgType: "boolean" },
      { name: "created_at", pgType: "timestamptz" },
      { name: "updated_at", pgType: "timestamptz" },
      { name: "row_version", pgType: "integer" },
    ],
  },
  {
    table: "shifts",
    label: "Shifts",
    primaryKey: "id",
    columns: [
      { name: "id", pgType: "uuid" },
      { name: "store_id", pgType: "text" },
      { name: "terminal_id", pgType: "text" },
      { name: "terminal_name", pgType: "text" },
      { name: "opened_by_name", pgType: "text" },
      { name: "opened_by_staff_id", pgType: "text" },
      { name: "opened_by_role", pgType: "text" },
      { name: "closed_by_name", pgType: "text" },
      { name: "closed_by_staff_id", pgType: "text" },
      { name: "closed_by_role", pgType: "text" },
      { name: "opened_at", pgType: "timestamptz" },
      { name: "closed_at", pgType: "timestamptz" },
      { name: "opening_float", pgType: "numeric(18,4)" },
      { name: "counted_cash", pgType: "numeric(18,4)" },
      { name: "expected_cash", pgType: "numeric(18,4)" },
      { name: "note", pgType: "text" },
      { name: "overdue", pgType: "boolean" },
      { name: "created_at", pgType: "timestamptz" },
      { name: "updated_at", pgType: "timestamptz" },
      { name: "status", pgType: "text" },
      { name: "closing_float", pgType: "numeric(18,4)" },
      { name: "user_id", pgType: "uuid" },
      { name: "row_version", pgType: "integer" },
      { name: "counted_card", pgType: "numeric(18,4)" },
      { name: "counted_digital", pgType: "numeric(18,4)" },
      { name: "expected_card", pgType: "numeric(18,4)" },
      { name: "expected_digital", pgType: "numeric(18,4)" },
      { name: "variance_cash", pgType: "numeric(18,4)" },
      { name: "variance_card", pgType: "numeric(18,4)" },
      { name: "variance_digital", pgType: "numeric(18,4)" },
      { name: "variance_total", pgType: "numeric(18,4)" },
    ],
  },
  {
    table: "shift_sessions",
    label: "Shift sessions",
    primaryKey: "id",
    columns: [
      { name: "id", pgType: "uuid" },
      { name: "shift_id", pgType: "text" },
      { name: "store_id", pgType: "text" },
      { name: "terminal_id", pgType: "text" },
      { name: "terminal_name", pgType: "text" },
      { name: "staff_id", pgType: "text" },
      { name: "staff_name", pgType: "text" },
      { name: "role", pgType: "text" },
      { name: "signed_in_at", pgType: "timestamptz" },
      { name: "signed_out_at", pgType: "timestamptz" },
      { name: "created_at", pgType: "timestamptz" },
      { name: "updated_at", pgType: "timestamptz" },
      { name: "row_version", pgType: "integer" },
    ],
  },
  {
    table: "drawer_events",
    label: "Drawer events",
    primaryKey: "id",
    columns: [
      { name: "id", pgType: "uuid" },
      { name: "store_id", pgType: "text" },
      { name: "terminal_id", pgType: "text" },
      { name: "shift_id", pgType: "text" },
      { name: "staff_id", pgType: "text" },
      { name: "staff_name", pgType: "text" },
      { name: "role", pgType: "text" },
      { name: "reason", pgType: "text" },
      { name: "note", pgType: "text" },
      { name: "approved_by", pgType: "text" },
      { name: "created_at", pgType: "timestamptz" },
    ],
  },
  {
    table: "sales",
    label: "Sales",
    primaryKey: "id",
    columns: [
      { name: "id", pgType: "uuid" },
      { name: "bill_number", pgType: "text" },
      { name: "member_id", pgType: "uuid" },
      { name: "store_id", pgType: "text" },
      { name: "cashier_name", pgType: "text" },
      { name: "subtotal_amount", pgType: "numeric(18,4)" },
      { name: "total_amount", pgType: "numeric(18,4)" },
      { name: "discount_amount", pgType: "numeric(18,4)" },
      { name: "tax_amount", pgType: "numeric(18,4)" },
      { name: "payment_type", pgType: "text" },
      { name: "points_earned", pgType: "numeric(18,4)" },
      { name: "points_redeemed", pgType: "numeric(18,4)" },
      { name: "is_exchange", pgType: "boolean" },
      { name: "original_bill_number", pgType: "text" },
      { name: "is_refunded", pgType: "boolean" },
      { name: "created_at", pgType: "timestamptz" },
      { name: "shift_id", pgType: "text" },
      { name: "paid_amount", pgType: "numeric(18,4)" },
      { name: "change_amount", pgType: "numeric(18,4)" },
      { name: "exchange_credit", pgType: "numeric(18,4)" },
      { name: "exchanged_to_bill_number", pgType: "text" },
      { name: "coupon_code", pgType: "text" },
      { name: "coupon_promo_id", pgType: "text" },
      { name: "coupon_scope", pgType: "text" },
      { name: "coupon_discount", pgType: "numeric(18,4)" },
      { name: "payments", pgType: "jsonb" },
      { name: "client_transaction_id", pgType: "text", classification: "required" as const },
      { name: "cashier_id", pgType: "text" },
      { name: "created_by", pgType: "text" },
      { name: "updated_by", pgType: "text" },
      { name: "row_version", pgType: "integer" },
      { name: "store_name_snapshot", pgType: "text" },
      { name: "store_address_snapshot", pgType: "text" },
    ],
  },
  {
    table: "sale_items",
    label: "Sale items",
    primaryKey: "id",
    columns: [
      { name: "id", pgType: "uuid" },
      { name: "sale_id", pgType: "uuid" },
      { name: "product_id", pgType: "uuid" },
      { name: "product_name", pgType: "text" },
      { name: "unit_price", pgType: "numeric(18,4)" },
      { name: "quantity", pgType: "integer" },
      { name: "discount_percent", pgType: "numeric(9,4)" },
      { name: "discount_amount", pgType: "numeric(18,4)" },
      { name: "is_return", pgType: "boolean" },
      { name: "created_at", pgType: "timestamptz" },
      { name: "tax_rate", pgType: "numeric(9,4)" },
      { name: "is_foc", pgType: "boolean" },
      { name: "promo_id", pgType: "text" },
      { name: "coupon_code", pgType: "text" },
      { name: "coupon_discount", pgType: "numeric(18,4)" },
      { name: "unit_cost", pgType: "numeric(18,4)" },
      { name: "row_version", pgType: "integer" },
    ],
  },
  {
    table: "payment_transactions",
    label: "Payments",
    primaryKey: "id",
    columns: [
      { name: "id", pgType: "text" },
      { name: "source_type", pgType: "text" },
      { name: "sale_id", pgType: "text" },
      { name: "booking_id", pgType: "text" },
      { name: "member_id", pgType: "text" },
      { name: "store_id", pgType: "text" },
      { name: "shift_id", pgType: "text" },
      { name: "terminal_id", pgType: "text" },
      { name: "amount", pgType: "numeric(18,4)" },
      { name: "method", pgType: "text" },
      { name: "kind", pgType: "text" },
      { name: "reference", pgType: "text" },
      { name: "cashier_id", pgType: "text" },
      { name: "cashier_name", pgType: "text" },
      { name: "note", pgType: "text" },
      { name: "paid_at", pgType: "timestamptz" },
      { name: "created_at", pgType: "timestamptz" },
      { name: "updated_at", pgType: "timestamptz" },
      { name: "row_version", pgType: "integer" },
      { name: "status", pgType: "text" },
      { name: "metadata", pgType: "jsonb" },
      { name: "client_transaction_id", pgType: "text", classification: "required" as const },
    ],
    indexes: [
      {
        name: "payment_transactions_client_txn_idx",
        sql: 'create unique index if not exists "payment_transactions_client_txn_idx" on public.payment_transactions (client_transaction_id) where client_transaction_id is not null;',
        dependsOnColumns: ["client_transaction_id"],
      },
    ],
  },
  {
    table: "item_activity_logs",
    label: "Item activity",
    primaryKey: "id",
    columns: [
      { name: "id", pgType: "text" },
      { name: "product_id", pgType: "text" },
      { name: "product_name", pgType: "text" },
      { name: "sku", pgType: "text" },
      { name: "barcode", pgType: "text" },
      { name: "store_id", pgType: "text" },
      { name: "terminal_id", pgType: "text" },
      { name: "activity_type", pgType: "text" },
      { name: "reference", pgType: "text" },
      { name: "quantity_delta", pgType: "integer" },
      { name: "stock_before", pgType: "integer" },
      { name: "stock_after", pgType: "integer" },
      { name: "unit_cost", pgType: "numeric(18,4)" },
      { name: "staff_id", pgType: "text" },
      { name: "staff_name", pgType: "text" },
      { name: "role", pgType: "text" },
      { name: "note", pgType: "text" },
      { name: "created_at", pgType: "timestamptz" },
      { name: "row_version", pgType: "integer" },
    ],
  },
  {
    table: "purchase_orders",
    label: "Purchase orders",
    primaryKey: "id",
    columns: [
      { name: "id", pgType: "uuid" },
      { name: "po_number", pgType: "text" },
      { name: "supplier_name", pgType: "text" },
      { name: "operator_name", pgType: "text" },
      { name: "total_cost", pgType: "numeric(18,4)" },
      { name: "total_items_count", pgType: "integer" },
      { name: "created_at", pgType: "timestamptz" },
      { name: "supplier_id", pgType: "uuid" },
      { name: "store_id", pgType: "text" },
      { name: "store_code", pgType: "text" },
      { name: "invoice_date", pgType: "date" },
      { name: "invoice_entry_date", pgType: "timestamptz" },
      { name: "updated_at", pgType: "timestamptz" },
      { name: "row_version", pgType: "integer" },
      { name: "status", pgType: "text" },
    ],
  },
  {
    table: "purchase_order_items",
    label: "Purchase order items",
    primaryKey: "id",
    columns: [
      { name: "id", pgType: "uuid" },
      { name: "po_id", pgType: "uuid" },
      { name: "product_id", pgType: "uuid" },
      { name: "barcode", pgType: "text" },
      { name: "product_name", pgType: "text" },
      { name: "cost_price", pgType: "numeric(18,4)" },
      { name: "selling_price", pgType: "numeric(18,4)" },
      { name: "quantity_received", pgType: "integer" },
      { name: "subtotal_cost", pgType: "numeric(18,4)" },
      { name: "created_at", pgType: "timestamptz" },
      { name: "sku", pgType: "text" },
      { name: "updated_at", pgType: "timestamptz" },
      { name: "row_version", pgType: "integer" },
    ],
  },
  {
    table: "bookings",
    label: "Bookings",
    primaryKey: "id",
    columns: [
      { name: "id", pgType: "uuid" },
      { name: "ref", pgType: "text" },
      { name: "store_id", pgType: "text" },
      { name: "shift_id", pgType: "text" },
      { name: "customer_name", pgType: "text" },
      { name: "customer_phone", pgType: "text" },
      { name: "member_id", pgType: "uuid" },
      { name: "service_type_id", pgType: "text" },
      { name: "service_name", pgType: "text" },
      { name: "service_fee", pgType: "numeric(18,4)" },
      { name: "payment_timing", pgType: "text" },
      { name: "lines", pgType: "jsonb" },
      { name: "subtotal", pgType: "numeric(18,4)" },
      { name: "discount", pgType: "numeric(18,4)" },
      { name: "tax", pgType: "numeric(18,4)" },
      { name: "total", pgType: "numeric(18,4)" },
      { name: "paid", pgType: "numeric(18,4)" },
      { name: "due_date", pgType: "date" },
      { name: "note", pgType: "text" },
      { name: "cashier", pgType: "text" },
      { name: "status", pgType: "text" },
      { name: "sale_receipt_no", pgType: "text" },
      { name: "closed_at", pgType: "timestamptz" },
      { name: "racket_model", pgType: "text" },
      { name: "string_type", pgType: "text" },
      { name: "tension_main", pgType: "numeric(18,4)" },
      { name: "tension_cross", pgType: "numeric(18,4)" },
      { name: "tension_unit", pgType: "text" },
      { name: "grommet_notes", pgType: "text" },
      { name: "job_notes", pgType: "text" },
      { name: "dropped_off_at", pgType: "timestamptz" },
      { name: "promised_at", pgType: "timestamptz" },
      { name: "job_status", pgType: "text" },
      { name: "job_status_by", pgType: "text" },
      { name: "job_status_at", pgType: "timestamptz" },
      { name: "notify_whatsapp", pgType: "boolean" },
      { name: "created_at", pgType: "timestamptz" },
      { name: "updated_at", pgType: "timestamptz" },
      { name: "tag_id", pgType: "text" },
      { name: "intake_note", pgType: "text" },
      { name: "string_origin", pgType: "text" },
      { name: "string_source_product_id", pgType: "uuid" },
      { name: "grip_product_id", pgType: "uuid" },
      { name: "charges", pgType: "jsonb" },
      { name: "technician", pgType: "text" },
      { name: "liability_accepted", pgType: "boolean" },
      { name: "incident_note", pgType: "text" },
      { name: "row_version", pgType: "integer" },
    ],
  },
  {
    table: "booking_payments",
    label: "Booking payments",
    primaryKey: "id",
    columns: [
      { name: "id", pgType: "uuid" },
      { name: "booking_id", pgType: "uuid" },
      { name: "amount", pgType: "numeric(18,4)" },
      { name: "method", pgType: "text" },
      { name: "cashier", pgType: "text" },
      { name: "paid_at", pgType: "timestamptz" },
      { name: "created_at", pgType: "timestamptz" },
      { name: "row_version", pgType: "integer" },
    ],
  },
  {
    table: "stock_transfers",
    label: "Stock transfers",
    primaryKey: "id",
    columns: [
      { name: "id", pgType: "uuid" },
      { name: "ref", pgType: "text" },
      { name: "kind", pgType: "text" },
      { name: "transfer_scope", pgType: "text" },
      { name: "from_store_id", pgType: "text" },
      { name: "from_store_name", pgType: "text" },
      { name: "from_group_id", pgType: "text" },
      { name: "to_store_id", pgType: "text" },
      { name: "to_store_name", pgType: "text" },
      { name: "to_group_id", pgType: "text" },
      { name: "status", pgType: "text" },
      { name: "note", pgType: "text" },
      { name: "created_by", pgType: "text" },
      { name: "approved_by", pgType: "text" },
      { name: "approved_at", pgType: "timestamptz" },
      { name: "received_by", pgType: "text" },
      { name: "received_at", pgType: "timestamptz" },
      { name: "rejected_reason", pgType: "text" },
      { name: "created_at", pgType: "timestamptz" },
      { name: "updated_at", pgType: "timestamptz" },
      { name: "row_version", pgType: "integer" },
    ],
  },
  {
    table: "stock_transfer_items",
    label: "Transfer items",
    primaryKey: "id",
    columns: [
      { name: "id", pgType: "uuid" },
      { name: "transfer_id", pgType: "uuid" },
      { name: "product_id", pgType: "uuid" },
      { name: "barcode", pgType: "text" },
      { name: "sku", pgType: "text" },
      { name: "product_name", pgType: "text" },
      { name: "quantity", pgType: "integer" },
      { name: "quantity_received", pgType: "integer" },
      { name: "unit_cost", pgType: "numeric(18,4)" },
      { name: "created_at", pgType: "timestamptz" },
      { name: "row_version", pgType: "integer" },
    ],
  },
  {
    table: "stock_adjustments",
    label: "Stock adjustments",
    primaryKey: "id",
    columns: [
      { name: "id", pgType: "uuid" },
      { name: "product_id", pgType: "uuid" },
      { name: "product_name", pgType: "text" },
      { name: "sku", pgType: "text" },
      { name: "barcode", pgType: "text" },
      { name: "store_id", pgType: "text" },
      { name: "terminal_id", pgType: "text" },
      { name: "reason", pgType: "text" },
      { name: "note", pgType: "text" },
      { name: "previous_stock", pgType: "integer" },
      { name: "updated_stock", pgType: "integer" },
      { name: "delta", pgType: "integer" },
      { name: "cost_impact", pgType: "numeric(18,4)" },
      { name: "staff_id", pgType: "text" },
      { name: "staff_name", pgType: "text" },
      { name: "role", pgType: "text" },
      { name: "created_at", pgType: "timestamptz" },
      { name: "draft_id", pgType: "uuid" },
      { name: "row_version", pgType: "integer" },
    ],
  },
  {
    table: "stock_count_drafts",
    label: "Stock count drafts",
    primaryKey: "id",
    columns: [
      { name: "id", pgType: "uuid" },
      { name: "reference", pgType: "text" },
      { name: "store_id", pgType: "text" },
      { name: "store_code", pgType: "text" },
      { name: "terminal_id", pgType: "text" },
      { name: "staff_id", pgType: "text" },
      { name: "staff_name", pgType: "text" },
      { name: "status", pgType: "text" },
      { name: "reason", pgType: "text" },
      { name: "note", pgType: "text" },
      { name: "lines", pgType: "text" },
      { name: "line_count", pgType: "integer" },
      { name: "total_impact", pgType: "numeric(18,4)" },
      { name: "posted_at", pgType: "timestamptz" },
      { name: "posted_by", pgType: "text" },
      { name: "created_at", pgType: "timestamptz" },
      { name: "updated_at", pgType: "timestamptz" },
    ],
  },
  {
    table: "held_orders",
    label: "Held orders",
    primaryKey: "id",
    columns: [
      { name: "id", pgType: "text" },
      { name: "label", pgType: "text" },
      { name: "store_id", pgType: "text" },
      { name: "shift_id", pgType: "text" },
      { name: "held_by", pgType: "text" },
      { name: "total", pgType: "numeric(18,4)" },
      { name: "lines", pgType: "jsonb" },
      { name: "cart_discount", pgType: "numeric(18,4)" },
      { name: "cart_discount_type", pgType: "text" },
      { name: "exchange_ref", pgType: "text" },
      { name: "member_id", pgType: "text" },
      { name: "member_name", pgType: "text" },
      { name: "coupon", pgType: "jsonb" },
      { name: "note", pgType: "text" },
      { name: "cancelled_from", pgType: "text" },
      { name: "held_at", pgType: "timestamptz" },
      { name: "created_at", pgType: "timestamptz" },
      { name: "updated_at", pgType: "timestamptz" },
      { name: "row_version", pgType: "integer" },
    ],
  },
  {
    table: "audit_logs",
    label: "Audit log",
    primaryKey: "id",
    columns: [
      { name: "id", pgType: "uuid" },
      { name: "user_name", pgType: "text" },
      { name: "action_category", pgType: "text" },
      { name: "action_name", pgType: "text" },
      { name: "target_module", pgType: "text" },
      { name: "details", pgType: "jsonb" },
      { name: "created_at", pgType: "timestamptz" },
      { name: "user_id", pgType: "text" },
      { name: "action", pgType: "text" },
      { name: "entity", pgType: "text" },
      { name: "before_state", pgType: "jsonb" },
      { name: "after_state", pgType: "jsonb" },
    ],
  },
  {
    table: "pos_settings",
    label: "POS settings",
    primaryKey: "id",
    columns: [
      { name: "receipt_css", pgType: "text not null default ''" },
    ],
  },
  {
    table: "pos_store_settings",
    label: "Branch settings",
    primaryKey: "id",
    columns: [
      { name: "require_pin_terminal_reset", pgType: "boolean" },
      { name: "row_version", pgType: "integer not null default 1" },
      { name: "updated_by", pgType: "text" },
    ],
  },
];

/** Fast lookup by table name (lowercase). */
export const CENTRAL_SCHEMA_BY_TABLE: ReadonlyMap<string, CentralTableSchema> = new Map(
  CENTRAL_SCHEMA.map((t) => [t.table, t]),
);