/**
 * The one door to the cloud client for platform code.
 *
 * `src/integrations/supabase/*` is generated and regenerated by the platform,
 * so those files stay where they are. Everything under /platforms imports the
 * client from here instead, which keeps the generated path an implementation
 * detail of /core.
 */
export { supabase } from "@/integrations/supabase/client";
export type { Database } from "@/integrations/supabase/types";
