/**
 * Bumps the patch digit of package.json and mirrors the version into every
 * committed version source used by the build.
 *
 * The normal bump is monotonic against existing v* Git tags. This prevents a
 * repository/package version reset from producing an "upgrade" lower than an
 * already published release (for example v1.3.755 -> 1.3.188).
 *
 *   node scripts/bump-version.cjs          # bump past package + highest v* tag
 *   node scripts/bump-version.cjs --write  # only re-sync generated version files
 *   node scripts/bump-version.cjs --set 1.2.3
 */
const fs = require("node:fs");
const path = require("node:path");
const { execFileSync } = require("node:child_process");

const root = path.join(__dirname, "..");
const pkgPath = path.join(root, "package.json");
const lockPath = path.join(root, "package-lock.json");
const versionPath = path.join(root, "src", "version.ts");

const pkg = JSON.parse(fs.readFileSync(pkgPath, "utf8"));
const writeOnly = process.argv.includes("--write");
const setAt = process.argv.indexOf("--set");
const requested = setAt >= 0 ? process.argv[setAt + 1] : "";

function parseVersion(value) {
  const match = /^(\d+)\.(\d+)\.(\d+)$/.exec(String(value || ""));
  return match ? match.slice(1).map(Number) : null;
}

function compareVersions(a, b) {
  for (let i = 0; i < 3; i += 1) {
    if (a[i] !== b[i]) return a[i] - b[i];
  }
  return 0;
}

function highestTaggedVersion() {
  try {
    const output = execFileSync("git", ["tag", "--list", "v[0-9]*"], {
      cwd: root,
      encoding: "utf8",
      stdio: ["ignore", "pipe", "ignore"],
    });
    let highest = null;
    for (const tag of output.split(/\r?\n/)) {
      const parsed = parseVersion(tag.replace(/^v/, ""));
      if (parsed && (!highest || compareVersions(parsed, highest) > 0)) highest = parsed;
    }
    return highest;
  } catch {
    return null;
  }
}

function syncLockVersion(version) {
  if (!fs.existsSync(lockPath)) return;
  const lock = JSON.parse(fs.readFileSync(lockPath, "utf8"));
  lock.version = version;
  if (lock.packages && lock.packages[""]) {
    lock.packages[""].version = version;
  }
  fs.writeFileSync(lockPath, `${JSON.stringify(lock, null, 2)}\n`);
}

if (requested) {
  if (!parseVersion(requested)) {
    throw new Error(`Invalid release version: ${requested}`);
  }
  pkg.version = requested;
  fs.writeFileSync(pkgPath, `${JSON.stringify(pkg, null, 2)}\n`);
} else if (!writeOnly) {
  const packageVersion = parseVersion(pkg.version) || [1, 0, 0];
  const tagVersion = highestTaggedVersion();
  const base =
    tagVersion && compareVersions(tagVersion, packageVersion) > 0 ? tagVersion : packageVersion;
  pkg.version = `${base[0]}.${base[1]}.${base[2] + 1}`;
  fs.writeFileSync(pkgPath, `${JSON.stringify(pkg, null, 2)}\n`);
}

syncLockVersion(pkg.version);

fs.writeFileSync(
  versionPath,
  `// Generated by scripts/bump-version.cjs — do not edit by hand.\nexport const APP_VERSION = "${pkg.version}";\n`,
);

process.stdout.write(`${pkg.version}\n`);
