/**
 * Bumps the patch digit of package.json (1.0.0 -> 1.0.1) and mirrors the new
 * value into src/version.ts so the app, the installer and the update feed all
 * report the same number. Prints the new version on stdout.
 *
 *   node scripts/bump-version.cjs          # bump patch
 *   node scripts/bump-version.cjs --write  # only regenerate src/version.ts
 *   node scripts/bump-version.cjs --set 1.2.3
 */
const fs = require("node:fs");
const path = require("node:path");

const root = path.join(__dirname, "..");
const pkgPath = path.join(root, "package.json");
const versionPath = path.join(root, "src", "version.ts");

const pkg = JSON.parse(fs.readFileSync(pkgPath, "utf8"));
const writeOnly = process.argv.includes("--write");
const setAt = process.argv.indexOf("--set");
const requested = setAt >= 0 ? process.argv[setAt + 1] : "";

if (requested) {
  if (!/^\d+\.\d+\.\d+$/.test(requested)) {
    throw new Error(`Invalid release version: ${requested}`);
  }
  pkg.version = requested;
  fs.writeFileSync(pkgPath, `${JSON.stringify(pkg, null, 2)}\n`);
} else if (!writeOnly) {
  const [major = 1, minor = 0, patch = 0] = String(pkg.version || "1.0.0")
    .split(".")
    .map((n) => Number.parseInt(n, 10) || 0);
  pkg.version = `${major}.${minor}.${patch + 1}`;
  fs.writeFileSync(pkgPath, `${JSON.stringify(pkg, null, 2)}\n`);
}

fs.writeFileSync(
  versionPath,
  `// Generated by scripts/bump-version.cjs — do not edit by hand.\nexport const APP_VERSION = "${pkg.version}";\n`,
);

process.stdout.write(`${pkg.version}\n`);
