/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as DisplayRouteImport } from './routes/display'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as MembersRouteImport } from './routes/members'
import { Route as PromotionsRouteImport } from './routes/promotions'
import { Route as PurchasingRouteImport } from './routes/purchasing'
import { Route as ReceiptsRouteImport } from './routes/receipts'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ShiftsRouteImport } from './routes/shifts'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as StoresRouteImport } from './routes/stores'
import { Route as TransfersRouteImport } from './routes/transfers'
import { Route as SettingsDisplayRouteImport } from './routes/settings.display'
import { Route as SettingsTaxRouteImport } from './routes/settings.tax'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const DisplayRoute = DisplayRouteImport.update({
  id: '/display',
  path: '/display',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const PromotionsRoute = PromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasingRoute = PurchasingRouteImport.update({
  id: '/purchasing',
  path: '/purchasing',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptsRoute = ReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ShiftsRoute = ShiftsRouteImport.update({
  id: '/shifts',
  path: '/shifts',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresRoute = StoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => rootRouteImport,
} as any)
const TransfersRoute = TransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsDisplayRoute = SettingsDisplayRouteImport.update({
  id: '/display',
  path: '/display',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsTaxRoute = SettingsTaxRouteImport.update({
  id: '/tax',
  path: '/tax',
  getParentRoute: () => SettingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/bookings': typeof BookingsRoute
  '/display': typeof DisplayRoute
  '/inventory': typeof InventoryRoute
  '/members': typeof MembersRoute
  '/promotions': typeof PromotionsRoute
  '/purchasing': typeof PurchasingRoute
  '/receipts': typeof ReceiptsRoute
  '/settings': typeof SettingsRouteWithChildren
  '/shifts': typeof ShiftsRoute
  '/staff': typeof StaffRoute
  '/stores': typeof StoresRoute
  '/transfers': typeof TransfersRoute
  '/settings/display': typeof SettingsDisplayRoute
  '/settings/tax': typeof SettingsTaxRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/bookings': typeof BookingsRoute
  '/display': typeof DisplayRoute
  '/inventory': typeof InventoryRoute
  '/members': typeof MembersRoute
  '/promotions': typeof PromotionsRoute
  '/purchasing': typeof PurchasingRoute
  '/receipts': typeof ReceiptsRoute
  '/settings': typeof SettingsRouteWithChildren
  '/shifts': typeof ShiftsRoute
  '/staff': typeof StaffRoute
  '/stores': typeof StoresRoute
  '/transfers': typeof TransfersRoute
  '/settings/display': typeof SettingsDisplayRoute
  '/settings/tax': typeof SettingsTaxRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/bookings': typeof BookingsRoute
  '/display': typeof DisplayRoute
  '/inventory': typeof InventoryRoute
  '/members': typeof MembersRoute
  '/promotions': typeof PromotionsRoute
  '/purchasing': typeof PurchasingRoute
  '/receipts': typeof ReceiptsRoute
  '/settings': typeof SettingsRouteWithChildren
  '/shifts': typeof ShiftsRoute
  '/staff': typeof StaffRoute
  '/stores': typeof StoresRoute
  '/transfers': typeof TransfersRoute
  '/settings/display': typeof SettingsDisplayRoute
  '/settings/tax': typeof SettingsTaxRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/bookings'
    | '/display'
    | '/inventory'
    | '/members'
    | '/promotions'
    | '/purchasing'
    | '/receipts'
    | '/settings'
    | '/shifts'
    | '/staff'
    | '/stores'
    | '/transfers'
    | '/settings/display'
    | '/settings/tax'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/bookings'
    | '/display'
    | '/inventory'
    | '/members'
    | '/promotions'
    | '/purchasing'
    | '/receipts'
    | '/settings'
    | '/shifts'
    | '/staff'
    | '/stores'
    | '/transfers'
    | '/settings/display'
    | '/settings/tax'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/bookings'
    | '/display'
    | '/inventory'
    | '/members'
    | '/promotions'
    | '/purchasing'
    | '/receipts'
    | '/settings'
    | '/shifts'
    | '/staff'
    | '/stores'
    | '/transfers'
    | '/settings/display'
    | '/settings/tax'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  BookingsRoute: typeof BookingsRoute
  DisplayRoute: typeof DisplayRoute
  InventoryRoute: typeof InventoryRoute
  MembersRoute: typeof MembersRoute
  PromotionsRoute: typeof PromotionsRoute
  PurchasingRoute: typeof PurchasingRoute
  ReceiptsRoute: typeof ReceiptsRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  ShiftsRoute: typeof ShiftsRoute
  StaffRoute: typeof StaffRoute
  StoresRoute: typeof StoresRoute
  TransfersRoute: typeof TransfersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/display': {
      id: '/display'
      path: '/display'
      fullPath: '/display'
      preLoaderRoute: typeof DisplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promotions': {
      id: '/promotions'
      path: '/promotions'
      fullPath: '/promotions'
      preLoaderRoute: typeof PromotionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchasing': {
      id: '/purchasing'
      path: '/purchasing'
      fullPath: '/purchasing'
      preLoaderRoute: typeof PurchasingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipts': {
      id: '/receipts'
      path: '/receipts'
      fullPath: '/receipts'
      preLoaderRoute: typeof ReceiptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shifts': {
      id: '/shifts'
      path: '/shifts'
      fullPath: '/shifts'
      preLoaderRoute: typeof ShiftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores': {
      id: '/stores'
      path: '/stores'
      fullPath: '/stores'
      preLoaderRoute: typeof StoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transfers': {
      id: '/transfers'
      path: '/transfers'
      fullPath: '/transfers'
      preLoaderRoute: typeof TransfersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/display': {
      id: '/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof SettingsDisplayRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/tax': {
      id: '/settings/tax'
      path: '/tax'
      fullPath: '/settings/tax'
      preLoaderRoute: typeof SettingsTaxRouteImport
      parentRoute: typeof SettingsRoute
    }
  }
}

interface SettingsRouteChildren {
  SettingsDisplayRoute: typeof SettingsDisplayRoute
  SettingsTaxRoute: typeof SettingsTaxRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsDisplayRoute: SettingsDisplayRoute,
  SettingsTaxRoute: SettingsTaxRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  BookingsRoute: BookingsRoute,
  DisplayRoute: DisplayRoute,
  InventoryRoute: InventoryRoute,
  MembersRoute: MembersRoute,
  PromotionsRoute: PromotionsRoute,
  PurchasingRoute: PurchasingRoute,
  ReceiptsRoute: ReceiptsRoute,
  SettingsRoute: SettingsRouteWithChildren,
  ShiftsRoute: ShiftsRoute,
  StaffRoute: StaffRoute,
  StoresRoute: StoresRoute,
  TransfersRoute: TransfersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
