/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as DisplayRouteImport } from './routes/display'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as MembersRouteImport } from './routes/members'
import { Route as PromotionsRouteImport } from './routes/promotions'
import { Route as PurchasingRouteImport } from './routes/purchasing'
import { Route as ReceiptsRouteImport } from './routes/receipts'
import { Route as ShiftsRouteImport } from './routes/shifts'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as StoresRouteImport } from './routes/stores'
import { Route as TransfersRouteImport } from './routes/transfers'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as SettingsDisplayRouteImport } from './routes/settings.display'
import { Route as SettingsElementsRouteImport } from './routes/settings.elements'
import { Route as SettingsIdentityRouteImport } from './routes/settings.identity'
import { Route as SettingsLinesRouteImport } from './routes/settings.lines'
import { Route as SettingsPaymentRouteImport } from './routes/settings.payment'
import { Route as SettingsQrRouteImport } from './routes/settings.qr'
import { Route as SettingsSyncRouteImport } from './routes/settings.sync'
import { Route as SettingsTaxRouteImport } from './routes/settings.tax'
import { Route as SettingsTypeRouteImport } from './routes/settings.type'
import { Route as SettingsWhatsappRouteImport } from './routes/settings.whatsapp'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const DisplayRoute = DisplayRouteImport.update({
  id: '/display',
  path: '/display',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const PromotionsRoute = PromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasingRoute = PurchasingRouteImport.update({
  id: '/purchasing',
  path: '/purchasing',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptsRoute = ReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => rootRouteImport,
} as any)
const ShiftsRoute = ShiftsRouteImport.update({
  id: '/shifts',
  path: '/shifts',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresRoute = StoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => rootRouteImport,
} as any)
const TransfersRoute = TransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsDisplayRoute = SettingsDisplayRouteImport.update({
  id: '/settings/display',
  path: '/settings/display',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsElementsRoute = SettingsElementsRouteImport.update({
  id: '/settings/elements',
  path: '/settings/elements',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIdentityRoute = SettingsIdentityRouteImport.update({
  id: '/settings/identity',
  path: '/settings/identity',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsLinesRoute = SettingsLinesRouteImport.update({
  id: '/settings/lines',
  path: '/settings/lines',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsPaymentRoute = SettingsPaymentRouteImport.update({
  id: '/settings/payment',
  path: '/settings/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsQrRoute = SettingsQrRouteImport.update({
  id: '/settings/qr',
  path: '/settings/qr',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSyncRoute = SettingsSyncRouteImport.update({
  id: '/settings/sync',
  path: '/settings/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsTaxRoute = SettingsTaxRouteImport.update({
  id: '/settings/tax',
  path: '/settings/tax',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsTypeRoute = SettingsTypeRouteImport.update({
  id: '/settings/type',
  path: '/settings/type',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsWhatsappRoute = SettingsWhatsappRouteImport.update({
  id: '/settings/whatsapp',
  path: '/settings/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/bookings': typeof BookingsRoute
  '/display': typeof DisplayRoute
  '/inventory': typeof InventoryRoute
  '/members': typeof MembersRoute
  '/promotions': typeof PromotionsRoute
  '/purchasing': typeof PurchasingRoute
  '/receipts': typeof ReceiptsRoute
  '/shifts': typeof ShiftsRoute
  '/staff': typeof StaffRoute
  '/stores': typeof StoresRoute
  '/transfers': typeof TransfersRoute
  '/settings/display': typeof SettingsDisplayRoute
  '/settings/elements': typeof SettingsElementsRoute
  '/settings/identity': typeof SettingsIdentityRoute
  '/settings/lines': typeof SettingsLinesRoute
  '/settings/payment': typeof SettingsPaymentRoute
  '/settings/qr': typeof SettingsQrRoute
  '/settings/sync': typeof SettingsSyncRoute
  '/settings/tax': typeof SettingsTaxRoute
  '/settings/type': typeof SettingsTypeRoute
  '/settings/whatsapp': typeof SettingsWhatsappRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/bookings': typeof BookingsRoute
  '/display': typeof DisplayRoute
  '/inventory': typeof InventoryRoute
  '/members': typeof MembersRoute
  '/promotions': typeof PromotionsRoute
  '/purchasing': typeof PurchasingRoute
  '/receipts': typeof ReceiptsRoute
  '/shifts': typeof ShiftsRoute
  '/staff': typeof StaffRoute
  '/stores': typeof StoresRoute
  '/transfers': typeof TransfersRoute
  '/settings/display': typeof SettingsDisplayRoute
  '/settings/elements': typeof SettingsElementsRoute
  '/settings/identity': typeof SettingsIdentityRoute
  '/settings/lines': typeof SettingsLinesRoute
  '/settings/payment': typeof SettingsPaymentRoute
  '/settings/qr': typeof SettingsQrRoute
  '/settings/sync': typeof SettingsSyncRoute
  '/settings/tax': typeof SettingsTaxRoute
  '/settings/type': typeof SettingsTypeRoute
  '/settings/whatsapp': typeof SettingsWhatsappRoute
  '/settings': typeof SettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/bookings': typeof BookingsRoute
  '/display': typeof DisplayRoute
  '/inventory': typeof InventoryRoute
  '/members': typeof MembersRoute
  '/promotions': typeof PromotionsRoute
  '/purchasing': typeof PurchasingRoute
  '/receipts': typeof ReceiptsRoute
  '/shifts': typeof ShiftsRoute
  '/staff': typeof StaffRoute
  '/stores': typeof StoresRoute
  '/transfers': typeof TransfersRoute
  '/settings/display': typeof SettingsDisplayRoute
  '/settings/elements': typeof SettingsElementsRoute
  '/settings/identity': typeof SettingsIdentityRoute
  '/settings/lines': typeof SettingsLinesRoute
  '/settings/payment': typeof SettingsPaymentRoute
  '/settings/qr': typeof SettingsQrRoute
  '/settings/sync': typeof SettingsSyncRoute
  '/settings/tax': typeof SettingsTaxRoute
  '/settings/type': typeof SettingsTypeRoute
  '/settings/whatsapp': typeof SettingsWhatsappRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/bookings'
    | '/display'
    | '/inventory'
    | '/members'
    | '/promotions'
    | '/purchasing'
    | '/receipts'
    | '/shifts'
    | '/staff'
    | '/stores'
    | '/transfers'
    | '/settings/display'
    | '/settings/elements'
    | '/settings/identity'
    | '/settings/lines'
    | '/settings/payment'
    | '/settings/qr'
    | '/settings/sync'
    | '/settings/tax'
    | '/settings/type'
    | '/settings/whatsapp'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/bookings'
    | '/display'
    | '/inventory'
    | '/members'
    | '/promotions'
    | '/purchasing'
    | '/receipts'
    | '/shifts'
    | '/staff'
    | '/stores'
    | '/transfers'
    | '/settings/display'
    | '/settings/elements'
    | '/settings/identity'
    | '/settings/lines'
    | '/settings/payment'
    | '/settings/qr'
    | '/settings/sync'
    | '/settings/tax'
    | '/settings/type'
    | '/settings/whatsapp'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/bookings'
    | '/display'
    | '/inventory'
    | '/members'
    | '/promotions'
    | '/purchasing'
    | '/receipts'
    | '/shifts'
    | '/staff'
    | '/stores'
    | '/transfers'
    | '/settings/display'
    | '/settings/elements'
    | '/settings/identity'
    | '/settings/lines'
    | '/settings/payment'
    | '/settings/qr'
    | '/settings/sync'
    | '/settings/tax'
    | '/settings/type'
    | '/settings/whatsapp'
    | '/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  BookingsRoute: typeof BookingsRoute
  DisplayRoute: typeof DisplayRoute
  InventoryRoute: typeof InventoryRoute
  MembersRoute: typeof MembersRoute
  PromotionsRoute: typeof PromotionsRoute
  PurchasingRoute: typeof PurchasingRoute
  ReceiptsRoute: typeof ReceiptsRoute
  ShiftsRoute: typeof ShiftsRoute
  StaffRoute: typeof StaffRoute
  StoresRoute: typeof StoresRoute
  TransfersRoute: typeof TransfersRoute
  SettingsDisplayRoute: typeof SettingsDisplayRoute
  SettingsElementsRoute: typeof SettingsElementsRoute
  SettingsIdentityRoute: typeof SettingsIdentityRoute
  SettingsLinesRoute: typeof SettingsLinesRoute
  SettingsPaymentRoute: typeof SettingsPaymentRoute
  SettingsQrRoute: typeof SettingsQrRoute
  SettingsSyncRoute: typeof SettingsSyncRoute
  SettingsTaxRoute: typeof SettingsTaxRoute
  SettingsTypeRoute: typeof SettingsTypeRoute
  SettingsWhatsappRoute: typeof SettingsWhatsappRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/display': {
      id: '/display'
      path: '/display'
      fullPath: '/display'
      preLoaderRoute: typeof DisplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promotions': {
      id: '/promotions'
      path: '/promotions'
      fullPath: '/promotions'
      preLoaderRoute: typeof PromotionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchasing': {
      id: '/purchasing'
      path: '/purchasing'
      fullPath: '/purchasing'
      preLoaderRoute: typeof PurchasingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipts': {
      id: '/receipts'
      path: '/receipts'
      fullPath: '/receipts'
      preLoaderRoute: typeof ReceiptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shifts': {
      id: '/shifts'
      path: '/shifts'
      fullPath: '/shifts'
      preLoaderRoute: typeof ShiftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores': {
      id: '/stores'
      path: '/stores'
      fullPath: '/stores'
      preLoaderRoute: typeof StoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transfers': {
      id: '/transfers'
      path: '/transfers'
      fullPath: '/transfers'
      preLoaderRoute: typeof TransfersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/display': {
      id: '/settings/display'
      path: '/settings/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof SettingsDisplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/elements': {
      id: '/settings/elements'
      path: '/settings/elements'
      fullPath: '/settings/elements'
      preLoaderRoute: typeof SettingsElementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/identity': {
      id: '/settings/identity'
      path: '/settings/identity'
      fullPath: '/settings/identity'
      preLoaderRoute: typeof SettingsIdentityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/lines': {
      id: '/settings/lines'
      path: '/settings/lines'
      fullPath: '/settings/lines'
      preLoaderRoute: typeof SettingsLinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/payment': {
      id: '/settings/payment'
      path: '/settings/payment'
      fullPath: '/settings/payment'
      preLoaderRoute: typeof SettingsPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/qr': {
      id: '/settings/qr'
      path: '/settings/qr'
      fullPath: '/settings/qr'
      preLoaderRoute: typeof SettingsQrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/sync': {
      id: '/settings/sync'
      path: '/settings/sync'
      fullPath: '/settings/sync'
      preLoaderRoute: typeof SettingsSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/tax': {
      id: '/settings/tax'
      path: '/settings/tax'
      fullPath: '/settings/tax'
      preLoaderRoute: typeof SettingsTaxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/type': {
      id: '/settings/type'
      path: '/settings/type'
      fullPath: '/settings/type'
      preLoaderRoute: typeof SettingsTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/whatsapp': {
      id: '/settings/whatsapp'
      path: '/settings/whatsapp'
      fullPath: '/settings/whatsapp'
      preLoaderRoute: typeof SettingsWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  BookingsRoute: BookingsRoute,
  DisplayRoute: DisplayRoute,
  InventoryRoute: InventoryRoute,
  MembersRoute: MembersRoute,
  PromotionsRoute: PromotionsRoute,
  PurchasingRoute: PurchasingRoute,
  ReceiptsRoute: ReceiptsRoute,
  ShiftsRoute: ShiftsRoute,
  StaffRoute: StaffRoute,
  StoresRoute: StoresRoute,
  TransfersRoute: TransfersRoute,
  SettingsDisplayRoute: SettingsDisplayRoute,
  SettingsElementsRoute: SettingsElementsRoute,
  SettingsIdentityRoute: SettingsIdentityRoute,
  SettingsLinesRoute: SettingsLinesRoute,
  SettingsPaymentRoute: SettingsPaymentRoute,
  SettingsQrRoute: SettingsQrRoute,
  SettingsSyncRoute: SettingsSyncRoute,
  SettingsTaxRoute: SettingsTaxRoute,
  SettingsTypeRoute: SettingsTypeRoute,
  SettingsWhatsappRoute: SettingsWhatsappRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
