/**
 * No key-shaped value may live in the repository.
 *
 * The environment file was committed once, so this check keeps the situation
 * from getting worse: the ignore rules stay in place, the committed file may
 * never carry a real secret, and no source file may hardcode a project
 * address or key.
 */
import { describe, expect, it } from "vitest";
import { execFileSync } from "node:child_process";
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";

const root = process.cwd();

/** Files git actually tracks, or null when git is unavailable in this run. */
function trackedFiles(): string[] | null {
  try {
    return execFileSync("git", ["ls-files"], { cwd: root, encoding: "utf8" })
      .split("\n")
      .map((line) => line.trim())
      .filter(Boolean);
  } catch {
    return null;
  }
}

const SECRET_SHAPES = [
  /sb_secret_[A-Za-z0-9_-]{10,}/,
  /service_role[^\n]{0,40}ey[A-Za-z0-9_-]{20,}/i,
  /-----BEGIN [A-Z ]*PRIVATE KEY-----/,
];

describe("secrets hygiene", () => {
  it("keeps the environment file out of version control going forward", () => {
    const ignore = readFileSync(join(root, ".gitignore"), "utf8");
    expect(ignore).toMatch(/^\.env$/m);
    expect(ignore).toMatch(/^\.env\.\*$/m);
    expect(ignore).toMatch(/^!\.env\.example$/m);
  });

  it("never lets a real secret sit in a committed environment file", () => {
    for (const name of [".env", ".env.example"]) {
      const file = join(root, name);
      if (!existsSync(file)) continue;
      const text = readFileSync(file, "utf8");
      for (const shape of SECRET_SHAPES) {
        expect(shape.test(text), `${name} contains a secret-shaped value`).toBe(false);
      }
      // Server-only names may be listed, but never with a value.
      for (const key of [
        "POS_SUPABASE_SERVICE_ROLE_KEY",
        "SETTINGS_ENCRYPTION_KEY",
        "SECURITY_ALERTS_WEBHOOK_SECRET",
      ]) {
        const match = new RegExp(`^${key}=(.+)$`, "m").exec(text);
        expect(match?.[1]?.trim() ?? "", `${name} sets ${key}`).toBe("");
      }
    }
  });

  it("hardcodes no project address or key in source", () => {
    const files = trackedFiles();
    if (!files) return;
    const sources = files.filter(
      (f) =>
        /^(src|electron|scripts)\//.test(f) &&
        /\.(ts|tsx|js|cjs|mjs)$/.test(f) &&
        !f.includes("__tests__") &&
        // Generated by the platform, and public by design.
        !f.startsWith("src/integrations/supabase/"),
    );
    const offenders: string[] = [];
    for (const file of sources) {
      const text = readFileSync(join(root, file), "utf8");
      if (/https:\/\/[a-z0-9]{20}\.supabase\.co/.test(text)) offenders.push(`${file}: project address`);
      if (/sb_(publishable|secret)_[A-Za-z0-9_-]{10,}/.test(text)) offenders.push(`${file}: key`);
      for (const shape of SECRET_SHAPES) if (shape.test(text)) offenders.push(`${file}: secret`);
    }
    expect(offenders).toEqual([]);
  });
});
